@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = {{contentType}}
@apiKey = f271c81ff7084ee5b99a5091b42d486e

#### create user
# @name create_user
POST http://{{host}}/api/users HTTP/1.1
content-type: {{contentType}}

{
  "email": "dmitrij.patuk@gmx.de",
  "password": "1234567"
}

#### create user
# @name create_user
POST http://{{host}}/api/users HTTP/1.1
content-type: {{contentType}}

{
  "email": "dmitrij.patuk3@gmx.de",
  "password": "1234567"
}

#### update user
# @name update_user
PUT http://{{host}}/api/users HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "email": "dmitrij.patuk2@gmx.de",
  "password": "12345678"
}

#### login user
# @name login
@authToken = {{login.response.body.token}}
@refreshToken = {{login.response.body.refresh_token}}
@usesrId = {{login.response.body.id}}
POST http://{{host}}/api/login HTTP/1.1
content-type: {{contentType}}

{
  "email": "dmitrij.patuk3@gmx.de",
  "password": "1234567",
  "expires_in_seconds": 60
}

#### refresh user token
# @name refresh
@authToken = {{login.response.body.token}}
POST http://{{host}}/api/refresh HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{refreshToken}}

#### revoke user token
# @name revoke
POST http://{{host}}/api/revoke HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{refreshToken}}

#### Create Chirp
# @name create_chirp
@chirp_id = {{create_chirp.response.body.id}}
POST http://{{host}}/api/chirps HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "body" : "hallo test test test"
}

#### Delete Chirp
# @name delete_chirp
DELETE http://{{host}}/api/chirps/{{chirp_id}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}


#### get all chirps
# @name get_all_chirps
GET http://{{host}}/api/chirps HTTP/1.1
Authorization: Bearer {{authToken}}


#### get one chirp
GET http://{{host}}/api/chirps/{{chirp_id}} HTTP/1.1
Authorization: Bearer {{authToken}}


#### RESET DB

POST http://{{host}}/admin/reset HTTP/1.1
content-type: {{contentType}}


#### Send Webhook Event

POST http://{{host}}/api/polka/webhooks HTTP/1.1
content-type: {{contentType}}
Authorization: ApiKey {{apiKey}}

{
  "event": "user.upgraded",
  "data": {
    "user_id": "{{usesrId}}"
  }
}

#### Send Wrong Webhook Event

POST http://{{host}}/api/polka/webhooks HTTP/1.1
content-type: {{contentType}}

{
  "event": "user.upgradeds",
  "data": {
    "user_id": "{{usesrId}}"
  }
}