POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

#### bad words

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is kerfuffle! an opinion sharbert I fornax need to share with the world"
}

#### too long

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world This is an opinion I need to share This is an opinion I need to share withThis is an opinion I need to share withThis is an opinion I need to share withThis is an opinion I need to share withwith the world"
}

#### RESET DB

POST http://localhost:8080/admin/reset HTTP/1.1
content-type: application/json

#### create user

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "dmitrij.patuk@gmx.de",
  "password": "1234567"
}

#### login user

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "dmitrij.patuk@gmx.de",
  "password": "1234567",
  "expires_in_seconds": 5
}

#### Create Chirp

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI0NjNhNGM0OS03Y2RkLTQ5MjQtYjE0MC0wYzhmNTZjNmFiMjUiLCJleHAiOjE3MjkzNzQ1NTQsIm5iZiI6MTcyOTM3NDU0OSwiaWF0IjoxNzI5Mzc0NTQ5fQ.P4HZ4mCvmFBz7makkoQEjHpkv-1hetmbS-fcGy8B7JE

{
  "body" : "hallo",
  "user_id" : "463a4c49-7cdd-4924-b140-0c8f56c6ab25"
}

#### get all chirps

GET http://localhost:8080/api/chirps HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI0NjNhNGM0OS03Y2RkLTQ5MjQtYjE0MC0wYzhmNTZjNmFiMjUiLCJleHAiOjE3MjkzNzY1NjcsIm5iZiI6MTcyOTM3Mjk2NywiaWF0IjoxNzI5MzcyOTY3fQ.wHqhWudm0Gf9SnCWNcMEvft6ndPmmLlfe_1Uvjt98Lg


#### get one chirp

GET http://localhost:8080/api/chirps/9352b9cf-a1d9-4aa6-b640-958c3a21027c HTTP/1.1