POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

#### bad words

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is kerfuffle! an opinion sharbert I fornax need to share with the world"
}

#### too long

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world This is an opinion I need to share This is an opinion I need to share withThis is an opinion I need to share withThis is an opinion I need to share withThis is an opinion I need to share withwith the world"
}

#### RESET DB

POST http://localhost:8080/admin/reset HTTP/1.1
content-type: application/json

#### create user

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "dmitrij.patuk@gmx.de",
  "password": "1234567"
}

#### login user

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "dmitrij.patuk@gmx.de",
  "password": "12345678"
}

#### Create Chirp

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

{
  "body" : "hallo",
  "user_id" : "87cb947e-0fde-42a2-849a-1ea668f38876"
}

#### get all chirps

GET http://localhost:8080/api/chirps HTTP/1.1

#### get one chirp

GET http://localhost:8080/api/chirps/9352b9cf-a1d9-4aa6-b640-958c3a21027c HTTP/1.1